In [4]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [146]:
def softmax(x):
    return np.exp(x) / np.exp(x).sum()

In [179]:
def posone(x):
    p = x# - np.min(x)
    return p / p.sum()

In [191]:
A = np.zeros((N, N)); A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [192]:
for i in range(N-1):
    for j in range(N-1):
        A[i,j] = np.random.rand()

In [193]:
A

array([[0.06120139, 0.5287981 , 0.        ],
       [0.52197802, 0.16037171, 0.        ],
       [0.        , 0.        , 0.        ]])

In [194]:
for i in range(N-1):
    A[i, -1] = 1 - A[i].sum()
    A[i] = softmax(A[i])
    #A[i] = posone(A[i])

In [195]:
A

array([[0.24915797, 0.39769438, 0.35314765],
       [0.39812853, 0.27731903, 0.32455245],
       [0.        , 0.        , 0.        ]])

In [196]:
for j in range(N-1):
    A[-1, j] = 1 - A[:, j].sum()

In [197]:
A

array([[0.24915797, 0.39769438, 0.35314765],
       [0.39812853, 0.27731903, 0.32455245],
       [0.3527135 , 0.32498659, 0.        ]])

In [198]:
A.sum(0), A.sum(1)

(array([1.        , 1.        , 0.67770009]),
 array([1.        , 1.        , 0.67770009]))

In [199]:
A[-1, -1] = 1 - A[-1].sum()

In [200]:
A.sum(0), A.sum(1)

(array([1., 1., 1.]), array([1., 1., 1.]))